package utils;

import java.util.logging.Level;

import blockchain.Account;
import blockchain.Blockchain;
import logging.LogManager;

public class AccountCreator {
	
	public static Account create(double amount, String nickname) {
		if(!check(amount, nickname)) {return null; }
		
		if(Blockchain.getInstance().getAutogeneratedTokens() < amount) {
			LogManager.write(Level.SEVERE, "Error during creating account: There are not enough tokens availables at the moment");
			return null;
		}
		
		return new Account(amount, nickname);
		
	}
	
	//TODO: Aquí hay un potencial bug, no podrías comprarle a alguien que tuviese
	//más tokens que la propia cadena.
	
	public static Account buy(Account seller, double amount, String nickname) {
		if(!check(amount, nickname)) { return null; }
		if(seller.getAmount() < amount) {
			LogManager.write(Level.SEVERE, "Error during creating account: The seller hasn´t enough tokens");
			return null;
		}
		Account a = create(0, nickname);
		seller.send(a, amount-2, 2);
		return a;
	}
	
	private static boolean check(double amount, String nickname) {
		if (amount < 0) {
			LogManager.write(Level.SEVERE, "Error during creating account: The amount can´t be negative");
			return false;
		}
		if (nickname.isEmpty()) {
			LogManager.write(Level.SEVERE, "Error during creating account: The nickname is required");
			return false;
		}
		return true;
	}

}
